FROM      docker.elastic.co/kibana/kibana:5.4.0
MAINTAINER Alok Upadhyay <alokin.ntl@gmail.com>
ENV KIBANA_VERSION 5.4.0
#RUN kibana-plugin install https://github.com/DeanF/health_metric_vis/releases/download/v0.3.5/health_metric_vis-${KIBANA_VERSION}.zip
